# Generated by Django 4.0.4 on 2022-05-14 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200, verbose_name='Project name')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('target_end', models.DateField(verbose_name='Target end date')),
                ('actual_end', models.DateField(verbose_name='Actual end date')),
                ('created_on', models.DateField(verbose_name='Creation date')),
                ('modified_on', models.DateField(null=True, verbose_name='Change date')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_creator', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(verbose_name='Creation date')),
                ('modified_on', models.DateField(null=True, verbose_name='Change date')),
                ('assigned_project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.project')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='createdby', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ManyToManyField(null=True, related_name='modifiedby', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=255, verbose_name='Issue summary')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('identification_date', models.DateField(verbose_name='Identified on')),
                ('priority', models.CharField(max_length=30, verbose_name='Priority')),
                ('target_resolution', models.DateField(verbose_name='Planned resolution')),
                ('progress', models.TextField(null=True, verbose_name='Progress')),
                ('actual_resolution', models.DateField(null=True, verbose_name='Actual resolution')),
                ('res_summary', models.TextField(null=True, verbose_name='Resolution summary')),
                ('created_on', models.DateField(verbose_name='Creation date')),
                ('modified_on', models.DateField(null=True, verbose_name='Change date')),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_solver', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ManyToManyField(related_name='issue_owner', to=settings.AUTH_USER_MODEL)),
                ('identified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ManyToManyField(related_name='issue_modifier', to=settings.AUTH_USER_MODEL)),
                ('related_project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.project')),
            ],
        ),
    ]
