# Generated by Django 4.0.4 on 2022-05-14 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0002_alter_people_options_alter_people_modified_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='actual_end',
            field=models.DateField(blank=True, null=True, verbose_name='Actual end date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='modified_on',
            field=models.DateField(blank=True, null=True, verbose_name='Change date'),
        ),
    ]
