# Generated by Django 4.0.4 on 2022-05-14 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0003_alter_project_actual_end_alter_project_modified_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='actual_resolution',
            field=models.DateField(blank=True, null=True, verbose_name='Actual resolution'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_solver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='issue',
            name='modified_by',
            field=models.ManyToManyField(blank=True, related_name='issue_modifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='issue',
            name='modified_on',
            field=models.DateField(blank=True, null=True, verbose_name='Change date'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('l', 'Low'), ('m', 'Medium'), ('h', 'High'), ('e', 'Extra')], default='m', max_length=1, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='res_summary',
            field=models.TextField(blank=True, null=True, verbose_name='Resolution summary'),
        ),
        migrations.AlterField(
            model_name='people',
            name='assigned_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.project'),
        ),
        migrations.AlterField(
            model_name='people',
            name='modified_by',
            field=models.ManyToManyField(blank=True, related_name='modifiedby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='people',
            name='modified_on',
            field=models.DateField(blank=True, null=True, verbose_name='Change date'),
        ),
    ]
