# Generated by Django 4.0.4 on 2022-05-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_issue_actual_resolution_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='people',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='people',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='people',
            name='modified_on',
        ),
        migrations.AddField(
            model_name='issue',
            name='resolved',
            field=models.CharField(default=False, max_length=1, verbose_name='Status'),
        ),
    ]
