# Generated by Django 4.0.4 on 2022-05-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_remove_people_created_by_remove_people_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='created_on',
            field=models.DateField(auto_now_add=True, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='identification_date',
            field=models.DateField(auto_now_add=True, verbose_name='Identified on'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='resolved',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_on',
            field=models.DateField(auto_now_add=True, verbose_name='Creation date'),
        ),
    ]
