# Generated by Django 4.0.4 on 2022-05-17 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0011_issue_created_by_alter_issue_identified_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuemodification',
            name='modified_by',
        ),
        migrations.AddField(
            model_name='issuemodification',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_modifier', to=settings.AUTH_USER_MODEL),
        ),
    ]
