# Generated by Django 4.0.4 on 2022-05-17 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_alter_issueedit_modified_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueedit',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue', to='tracker.issue'),
        ),
    ]
