# Generated by Django 4.0.4 on 2022-05-17 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0016_alter_issueedit_issue'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalIssue',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('summary', models.CharField(max_length=255, verbose_name='Issue summary')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('identification_date', models.DateField(blank=True, editable=False, verbose_name='Identified on')),
                ('priority', models.CharField(choices=[('l', 'Low'), ('m', 'Medium'), ('h', 'High'), ('e', 'Extra')], default='m', max_length=1, verbose_name='Priority')),
                ('target_resolution', models.DateField(verbose_name='Planned resolution')),
                ('progress', models.TextField(null=True, verbose_name='Progress')),
                ('actual_resolution', models.DateField(blank=True, null=True, verbose_name='Actual resolution')),
                ('res_summary', models.TextField(blank=True, null=True, verbose_name='Resolution summary')),
                ('created_on', models.DateField(blank=True, editable=False, verbose_name='Creation date')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('assigned_to', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('identified_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('related_project', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tracker.project')),
            ],
            options={
                'verbose_name': 'historical issue',
                'verbose_name_plural': 'historical issues',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProject',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200, verbose_name='Project name')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('target_end', models.DateField(verbose_name='Target end date')),
                ('actual_end', models.DateField(blank=True, null=True, verbose_name='Actual end date')),
                ('created_on', models.DateField(blank=True, editable=False, verbose_name='Creation date')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical project',
                'verbose_name_plural': 'historical projects',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RemoveField(
            model_name='projectedit',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='projectedit',
            name='project',
        ),
        migrations.DeleteModel(
            name='IssueEdit',
        ),
        migrations.DeleteModel(
            name='ProjectEdit',
        ),
    ]
