# Generated by Django 4.0.4 on 2022-05-17 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0017_historicalissue_historicalproject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproject',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalproject',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='HistoricalIssue',
        ),
        migrations.DeleteModel(
            name='HistoricalProject',
        ),
    ]
