# Generated by Django 4.0.4 on 2022-05-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0018_remove_historicalproject_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='assigned_project',
        ),
        migrations.AddField(
            model_name='people',
            name='assigned_project',
            field=models.ManyToManyField(help_text='Assign project(s)', to='tracker.project'),
        ),
    ]
