# Generated by Django 4.0.4 on 2022-05-17 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0019_remove_people_assigned_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='assigned_project',
        ),
        migrations.CreateModel(
            name='AssignedProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.people')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.project')),
            ],
        ),
    ]
