# Generated by Django 4.0.4 on 2022-05-17 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0020_remove_people_assigned_project_assignedprojects'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to='tracker.people'),
        ),
        migrations.DeleteModel(
            name='AssignedProjects',
        ),
    ]
