# Generated by Django 4.0.4 on 2022-05-14 15:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='people',
            options={'verbose_name': 'People', 'verbose_name_plural': 'People'},
        ),
        migrations.AlterField(
            model_name='people',
            name='modified_by',
            field=models.ManyToManyField(related_name='modifiedby', to=settings.AUTH_USER_MODEL),
        ),
    ]
