# Generated by Django 4.0.4 on 2022-05-17 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0009_remove_issue_resolved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='modified_on',
        ),
        migrations.RemoveField(
            model_name='project',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='project',
            name='modified_on',
        ),
        migrations.AlterField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProjectModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_on', models.DateField(auto_now_add=True, verbose_name='Change date')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.project')),
            ],
        ),
        migrations.CreateModel(
            name='IssueModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_on', models.DateField(auto_now_add=True, verbose_name='Change date')),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.issue')),
                ('modified_by', models.ManyToManyField(blank=True, related_name='issue_modifier', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
