# Generated by Django 4.0.4 on 2022-05-17 09:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0012_remove_issuemodification_modified_by_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IssueModification',
            new_name='IssueEdit',
        ),
        migrations.RenameModel(
            old_name='ProjectModification',
            new_name='ProjectEdit',
        ),
    ]
