# Generated by Django 4.0.4 on 2022-05-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_rename_issuemodification_issueedit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueedit',
            name='modified_on',
            field=models.DateField(auto_now=True, verbose_name='Change date'),
        ),
    ]
