# Generated by Django 4.0.4 on 2022-05-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0023_people_deleted_alter_people_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='deleted',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='project',
            name='deleted',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
